# Generated by Django 4.0.3 on 2022-04-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur', models.CharField(max_length=248)),
                ('pitchTitle', models.TextField()),
                ('pitchIdea', models.TextField()),
                ('askAmount', models.DecimalField(decimal_places=4, max_digits=124)),
                ('equity', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.TextField(max_length=248)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=7, max_digits=10)),
                ('comment', models.CharField(max_length=500)),
                ('pitches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitches.pitches')),
            ],
        ),
    ]
